# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfigUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigDialog(object):
    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.resize(352, 159)
        self.widget = QtWidgets.QWidget(ConfigDialog)
        self.widget.setGeometry(QtCore.QRect(20, 10, 311, 144))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.apiKey = QtWidgets.QLineEdit(self.widget)
        self.apiKey.setObjectName("apiKey")
        self.verticalLayout.addWidget(self.apiKey)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.configButtonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.configButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.configButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.configButtonBox.setObjectName("configButtonBox")
        self.verticalLayout.addWidget(self.configButtonBox)

        self.retranslateUi(ConfigDialog)
        self.configButtonBox.accepted.connect(ConfigDialog.accept) # type: ignore
        self.configButtonBox.rejected.connect(ConfigDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConfigDialog)

    def retranslateUi(self, ConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigDialog.setWindowTitle(_translate("ConfigDialog", "Dialog"))
        self.label.setText(_translate("ConfigDialog", "Geoapify API Key:"))
