# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ForwardUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeocodingForm(object):
    def setupUi(self, GeocodingForm):
        GeocodingForm.setObjectName("GeocodingForm")
        GeocodingForm.resize(646, 601)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GeocodingForm.sizePolicy().hasHeightForWidth())
        GeocodingForm.setSizePolicy(sizePolicy)
        GeocodingForm.setStyleSheet("QGroupBox {\n"
"border: none\n"
"}")
        GeocodingForm.setSizeGripEnabled(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GeocodingForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formGroupBox = QtWidgets.QGroupBox(GeocodingForm)
        self.formGroupBox.setEnabled(True)
        self.formGroupBox.setAccessibleDescription("")
        self.formGroupBox.setAutoFillBackground(False)
        self.formGroupBox.setStyleSheet("QGroupBox {\n"
"border: none\n"
"}")
        self.formGroupBox.setFlat(True)
        self.formGroupBox.setCheckable(False)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout_2.setContentsMargins(0, 20, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.inputType = QtWidgets.QComboBox(self.formGroupBox)
        self.inputType.setStyleSheet("")
        self.inputType.setObjectName("inputType")
        self.inputType.addItem("")
        self.inputType.addItem("")
        self.inputType.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputType)
        self.verticalLayout.addWidget(self.formGroupBox)
        self.addressLabel = QtWidgets.QLabel(GeocodingForm)
        self.addressLabel.setObjectName("addressLabel")
        self.verticalLayout.addWidget(self.addressLabel)
        self.addressList = QtWidgets.QTextEdit(GeocodingForm)
        self.addressList.setPlaceholderText("")
        self.addressList.setObjectName("addressList")
        self.verticalLayout.addWidget(self.addressList)
        self.stepLabel = QtWidgets.QLabel(GeocodingForm)
        self.stepLabel.setObjectName("stepLabel")
        self.verticalLayout.addWidget(self.stepLabel)
        self.progressBar = QtWidgets.QProgressBar(GeocodingForm)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.address = QtWidgets.QLineEdit(GeocodingForm)
        self.address.setText("")
        self.address.setObjectName("address")
        self.verticalLayout.addWidget(self.address)
        self.buttonBox = QtWidgets.QDialogButtonBox(GeocodingForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridGroupBox = QtWidgets.QGroupBox(GeocodingForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox.sizePolicy().hasHeightForWidth())
        self.gridGroupBox.setSizePolicy(sizePolicy)
        self.gridGroupBox.setFlat(True)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gridGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.closeButton = QtWidgets.QPushButton(self.gridGroupBox)
        self.closeButton.setMinimumSize(QtCore.QSize(80, 0))
        self.closeButton.setMaximumSize(QtCore.QSize(614, 16777215))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.runButton = QtWidgets.QPushButton(self.gridGroupBox)
        self.runButton.setMinimumSize(QtCore.QSize(80, 0))
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.verticalLayout.addWidget(self.gridGroupBox, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(GeocodingForm)
        self.buttonBox.clicked['QAbstractButton*'].connect(GeocodingForm.accept) # type: ignore
        self.buttonBox.clicked['QAbstractButton*'].connect(GeocodingForm.reject) # type: ignore
        self.inputType.currentIndexChanged['int'].connect(GeocodingForm.updateListPlaceholder) # type: ignore
        self.runButton.clicked.connect(GeocodingForm.toggleProcessing) # type: ignore
        self.closeButton.clicked.connect(GeocodingForm.close) # type: ignore
        self.addressList.textChanged.connect(GeocodingForm.addressListChanged) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GeocodingForm)
        GeocodingForm.setTabOrder(self.addressList, self.address)

    def retranslateUi(self, GeocodingForm):
        _translate = QtCore.QCoreApplication.translate
        GeocodingForm.setWindowTitle(_translate("GeocodingForm", "Geoapify Geocoding"))
        self.label.setText(_translate("GeocodingForm", "1. Choose input type:"))
        self.inputType.setItemText(0, _translate("GeocodingForm", "Address"))
        self.inputType.setItemText(1, _translate("GeocodingForm", "Latitude,Longitude"))
        self.inputType.setItemText(2, _translate("GeocodingForm", "Longitude,Latitude"))
        self.addressLabel.setText(_translate("GeocodingForm", "2. Enter lines here:"))
        self.stepLabel.setText(_translate("GeocodingForm", "0 lines to process"))
        self.closeButton.setText(_translate("GeocodingForm", "Close"))
        self.runButton.setText(_translate("GeocodingForm", "Run"))
