# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ForwardUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeoCoding(object):
    def setupUi(self, GeoCoding):
        GeoCoding.setObjectName("GeoCoding")
        GeoCoding.resize(646, 150)
        self.gridLayout = QtWidgets.QGridLayout(GeoCoding)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addressLabel = QtWidgets.QLabel(GeoCoding)
        self.addressLabel.setObjectName("addressLabel")
        self.verticalLayout.addWidget(self.addressLabel)
        self.address = QtWidgets.QLineEdit(GeoCoding)
        self.address.setText("")
        self.address.setObjectName("address")
        self.verticalLayout.addWidget(self.address)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(GeoCoding)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(GeoCoding)
        self.buttonBox.accepted.connect(GeoCoding.accept) # type: ignore
        self.buttonBox.rejected.connect(GeoCoding.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GeoCoding)

    def retranslateUi(self, GeoCoding):
        _translate = QtCore.QCoreApplication.translate
        GeoCoding.setWindowTitle(_translate("GeoCoding", "GeoCoding"))
        self.addressLabel.setText(_translate("GeoCoding", "Free text address search:"))
